apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gustavo-velasquez
  namespace: namespace-gustavo-velasquez
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80